name: CD to Docker Hub

on:
  create:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Check Out Repo
            uses: actions/checkout@v2
          - name: Set up JDK 21
            uses: actions/setup-java@v2
            with:
              distribution: 'adopt'
              java-version: '21'
              # Optionally, you can specify java-package: jdk # For a specific JDK package
              
          - name: Save JAR artifact
            uses: actions/upload-artifact@v2
            with:
              name: Frontseat-JAR
              path: target/FrontSeat-1.0-SNAPSHOT.jar
             
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
   
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
   
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clitaxi:latest
   
          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}
